### ISSUE TITLE
v1.3.4 Errors on PDF and PNG Generation

### ISSUE THREAD

**Issue by camow7** [liady/ChatGPT-pdf#30]
Currently getting this error in Dev console for v1.3.4. I am using Brave Browser.

```
content_script.js:201 Uncaught TypeError: Cannot read properties of null (reading 'style')
    at Elements.fixLocation (content_script.js:201:17)
    at downloadThread (content_script.js:112:12)
    at downloadButton.onclick (content_script.js:89:5)
```

**Comment by brandonros** [comment]
fixed in https://github.com/liady/ChatGPT-pdf/pull/28/files

**Comment by adrianmarinwork** [comment]
Hello, I was a contributor once to this project and I see that liady stopped maintaining it. Because of that I have created my own version of the ChatGPT-pdf, called [ChatgptToPdf](https://github.com/adrianmarinwork/ChatgptToPdf), If you see that you have problems with this extension I invite you to try mine and see if your issues get fix, let's work together to improve it. Thank you!
