### ISSUE TITLE
Able to generate PDF & PNG at only once, next time gives error

### ISSUE THREAD

**Issue by adivaste** [liady/ChatGPT-pdf#31]
I'm able to generate the PDF and PNG image only at ones, for the second time it gives the errors as 
`Uncaught TypeError: Cannot read properties of null (reading 'style')
    at Elements.fixLocation (content_script.js:201:17)
    at downloadThread (content_script.js:112:12)
    at downloadButton.onclick (content_script.js:89:5)`

and 

`content_script.js:201 Uncaught TypeError: Cannot read properties of null (reading 'style')
    at Elements.fixLocation (content_script.js:201:17)
    at downloadThread (content_script.js:112:12)
    at downloadPdfButton.onclick (content_script.js:97:5)`

**Comment by brandonros** [comment]
fixed in https://github.com/liady/ChatGPT-pdf/pull/28/files
