### ISSUE TITLE
Issue Extension not working. Nothing works in extension.

### ISSUE THREAD

**Issue by faisal-fida** [liady/ChatGPT-pdf#35]
Uncaught TypeError: Cannot read properties of null (reading 'style')
    at Elements.fixLocation (content_script.js:200:17)
    at downloadThread (content_script.js:112:12)
    at downloadButton.onclick (content_script.js:89:5)
fixLocation @ content_script.js:200
downloadThread @ content_script.js:112
downloadButton.onclick @ content_script.js:89

**Comment by rmcc3** [comment]
Fixed in #34

**Comment by DumontHenry** [comment]
I still have the issue where the error shows the following : 
Uncaught TypeError: Cannot read properties of null (reading 'style')
    at Elements.fixLocation (content_script.js:200:17)
    at downloadThread (content_script.js:112:12)
    at downloadPdfButton.onclick (content_script.js:97:5)

**Comment by gaa23** [comment]
content_script.js:200 Uncaught TypeError: Cannot read properties of null (reading 'style')
    at Elements.fixLocation (content_script.js:200:17)
    at downloadThread (content_script.js:112:12)
    at downloadPdfButton.onclick (content_script.js:97:5)
