### ISSUE TITLE
Chrome addon does not work - Cannot read properties of null (reading 'style')

### ISSUE THREAD

**Issue by psymed** [liady/ChatGPT-pdf#45]
Chrome addon does not work - The below error is thrown on Console log:
```
Uncaught TypeError: Cannot read properties of null (reading 'style')
    at Elements.fixLocation (content_script.js:200:17)
    at downloadThread (content_script.js:112:12)
    at downloadButton.onclick (content_script.js:89:5)
fixLocation @ content_script.js:200
downloadThread @ content_script.js:112
downloadButton.onclick @ content_script.js:89
72The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
content_script.js:200 Uncaught TypeError: Cannot read properties of null (reading 'style')
    at Elements.fixLocation (content_script.js:200:17)
    at downloadThread (content_script.js:112:12)
    at downloadPdfButton.onclick (content_script.js:97:5)
fixLocation @ content_script.js:200
downloadThread @ content_script.js:112
downloadPdfButton.onclick @ content_script.js:97
content_script.js:275 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'cssRules')
    at getCssFromSheet (content_script.js:275:27)
    at getData (content_script.js:258:21)
    at sendRequest (content_script.js:239:16)
    at exportHtml.onclick (content_script.js:105:5)
getCssFromSheet @ content_script.js:275
getData @ content_script.js:258
sendRequest @ content_script.js:239
exportHtml.onclick @ content_script.js:105
```

**Comment by johnmchale** [comment]
Yes, I get a similar error 

<img width="541" alt="image" src="https://user-images.githubusercontent.com/38525955/221351232-c5096875-5b30-49df-8624-c03a6156a2c3.png">
